server:
  port: ${appPort:8080}
  servlet-path: /api

#SPRING MVC : Enable endpoints access (/admin/info...)

endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

info:
  app:
    name: '@project.artifactId@'
  build:
    version: '@project.version@'

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
      hostname: ${HOSTNAME}
      nonSecurePort: 8080
      
      
spring:
  application:
    name: springCloudService1
 
